FROM jupyter/base-notebook

USER root 

RUN apt-get update && apt-get -y install git

USER ${NB_UID}

ADD ciplatform.yml /tmp/

WORKDIR /tmp

RUN conda create -n iguide python=3.8

RUN conda install -n iguide mamba

RUN mamba env update --name iguide --file ciplatform.yml

RUN conda install ipykernel ipywidgets nb_conda_kernels nbgitpuller

RUN conda install -n iguide -c conda-forge ipympl

WORKDIR /home/jovyan
