# Author: Rajesh Kalyanam <rkalyana@purdue.edu>
# Adapted from: https://hub.docker.com/repository/docker/alexandermichels/cybergisx-dev
FROM jupyter/base-notebook:2023-06-13
#FROM jupyter/base-notebook:2022-07-25

USER root

RUN apt-get update && apt-get install --fix-missing -y --no-install-recommends \
    bc \
    git \
    g++ \
    make \
    libgl1-mesa-glx \
    lua5.3 \
    lua-bit32:amd64 \
    lua-posix:amd64 \
    lua-posix-dev \
    liblua5.3-0:amd64 \
    liblua5.3-dev:amd64 \
    tcl \
    tcl-dev \
    tcl8.6 \
    tcl8.6-dev:amd64 \
    libtcl8.6:amd64 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/

# installing Lmod
RUN update-alternatives --install /usr/bin/lua \
    lua-interpreter /usr/bin/lua5.3 130 \
    --slave /usr/share/man/man1/lua.1.gz lua-manual \
    /usr/share/man/man1/lua5.3.1.gz
RUN update-alternatives --install /usr/bin/luac \
    lua-compiler /usr/bin/luac5.3 130 \
    --slave /usr/share/man/man1/luac.1.gz lua-compiler-manual \
    /usr/share/man/man1/luac5.3.1.gz
RUN ln -sf /usr/lib/x86_64-linux-gnu/liblua5.3-posix.so \
    /usr/lib/x86_64-linux-gnu/lua/5.3/posix.so

RUN cd /tmp && \
    git clone https://github.com/TACC/Lmod && \
    cd Lmod && \
    ./configure --prefix=/usr/share && \
    make install && \
    cd / && \
    rm -rf /tmp/Lmod

RUN ln -s /usr/share/lmod/lmod/init/profile        /etc/profile.d/z00_lmod.sh && \
    ln -s /usr/share/lmod/lmod/init/cshrc          /etc/profile.d/z00_lmod.csh && \
    /bin/bash -c "source /etc/profile.d/z00_lmod.sh"

USER ${NB_UID}

RUN conda install ipykernel ipywidgets nb_conda_kernels nbgitpuller mamba jupyter_contrib_nbextensions

RUN pip install RISE

RUN jupyter nbextension enable init_cell/main --sys-prefix

RUN jupyter nbextension enable python-markdown/main --sys-prefix

RUN pip install -U --no-cache-dir --upgrade-strategy only-if-needed git+https://github.com/hydroshare/nbfetch

RUN jupyter server extension enable --py nbfetch

WORKDIR /home/jovyan

CMD ["start-notebook.sh","--NotebookApp.iopub_data_rate_limit=1e10"]
